- name: ssh deploy
  # You may pin to the exact commit or the version.
  # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
  uses: easingthemes/ssh-deploy@v2.2.11
  with:
    # Private Key
    SSH_PRIVATE_KEY: 
    # Remote host
    REMOTE_HOST: 
    # Remote user
    REMOTE_USER: 
    # Remote port
    REMOTE_PORT: # optional, default is 22
    # Source directory
    SOURCE: # optional, default is 
    # Target directory
    TARGET: # optional, default is /home/REMOTE_USER/
    # Arguments to pass to rsync
    ARGS: # optional, default is -rltgoDzvO
    # An array of folder to exclude
    EXCLUDE: # optional, default is 
